version: "3.9"

services:
  api:
    build: .
    container_name: api-orders
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orders_db
      - PORT=5001
    ports:
      - "5001:5001"

  db:
    image: postgres:16
    container_name: db-orders
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_db
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
